language: node_js
node_js:
  - "node"
cache: yarn
script: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 6d3652966d72ce7421f99ceca0ac20900d5512d1
  local_dir: dist
  on:
    branch: master